config/routes.rb
Rails.application.routes.draw do
  get 'login/new'
  resources :trees, except: :index
  resources :locations, only: [:index, :show]
  resources :users
  resources :login, only: [:new, :create]
  get '/register', to: "users#new"
  delete "/logout", to: "login#destroy"
  root "locations#index"
  # get 'sessions/new'
  # get '/login' => 'sessions#new'
  # post '/login' => 'sessions#create'
  # post '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :trees
  has_many :users, through: :trees
end

app/models/tree.rb
class Tree < ApplicationRecord
  belongs_to :user
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
   has_secure_password

  has_many :trees
  has_many :locations, through: :trees

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :find_user
  # before_action :authorized?

  def find_user
    @user_id = session[:user_id]
    @logged_in = !!@user_id
    if @logged_in
      @current_user = User.find(@user_id)
    end
  end

  def logout
    session[:user_id] = nil
  end

  def authorized?
    unless @logged_in
      return redirect_to locations_path
    end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params[:id])
    @trees = Tree.select{|t| t.location_id == @location.id}
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  # skip_before_action :authorized?, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user && @user.authenticate(params[:password])
      flash[:messages] = "Logging in #{@user.name}"
      session[:user_id] = @user.id
      redirect_to locations_path
    else
      flash[:messages] = "Incorrect username or password"
      redirect_to new_login_path
    end
  end

  def destroy
    logout
    redirect_to locations_path
  end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  def show
    @tree = Tree.find(params[:id])
  end

  def new
    @tree = Tree.new
    @trees = Tree.all
    @locations = Location.all
  end

  def create
    # byebug
    if @logged_in
      @tree = Tree.create(species: tree_params[:species], age: tree_params[:age], user_id: @current_user.id, location_id: tree_params[:location_id])
      session[:tree_id] = @tree.id
      redirect_to "/trees/#{@tree.id}"
    else
      flash[:messages] = "Must be logged in to plant a tree."
      redirect_to new_login_path
    end
  end

  def edit
    @tree = Tree.find(params[:id])
  end

  def update
    @tree = Tree.find(params[:id])
    @tree.update(location_id: params[:tree][:location_id])
    redirect_to @tree
  end

  private

  def tree_params
    params.require(:tree).permit(:species, :age, :user_id, :location_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @trees = Tree.select { |t| t.user_id == @user.id }
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.name = user_params[:name]
      @user.password = user_params[:password]
      @user.save
      redirect_to "/users"
    else
      flash[:errors] = @user.errors.full_messages
        redirect_to '/users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.valid?
    @user.update
    redirect_to "/users/#{users.id}"
    else
    flash[:erros] = @user.erros.full.messages
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="footer">
  <p><%= link_to 'Register', '/register' %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= link_to 'Login', new_login_path %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= link_to "Locations", locations_path %> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <%= link_to "Plant a Tree!", new_tree_path %></p>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GreenThumb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if @logged_in %>
        <p>Logged in as: <%= link_to @current_user.name, "/users/#{@current_user.id}" %></p>
        <div class="logged-in-status"><%= button_to "Log out #{@current_user.name}", "/logout", method: :delete %></div>
      <% else %>
        <p>
          <%= link_to "Log in", new_login_path %>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "Register", new_user_path %>
        </p>
      <% end %>
    </header>
    <div class="page-container">
      <div class="content-wrap">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/locations/index.html.erb
<h1>Locations</h1>
<% @locations.each do |loc| %>
  <h3><%= link_to loc.name, loc %></h3>
  <% if loc != @locations.last %>
    <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h3>
  <% end %>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<h2>Trees at this location:</h2>
<div class="show-page-list">
  <% @trees.each do |tree| %>
    <h3><%= link_to tree.species.capitalize, tree %>, planted by: <%= link_to User.find(tree.user_id).name, User.find(tree.user_id)  %></h3>
    <% if tree != @trees.last %>
      <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h3>
    <% end %>
  <% end %>
</div>

app/views/login/new.html.erb
<h1>Login</h1>
<br><br>

<%= form_tag "/login" do %>
  <%= label_tag :name %>&nbsp;&nbsp;
  <%= text_field_tag :name %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= label_tag :password %>&nbsp;&nbsp;
  <%= password_field_tag :password %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= submit_tag "Login!" %>
<% end %>

app/views/trees/edit.html.erb
<h1>Edit a Tree</h1>
<br><br>

<%= form_for @tree do |f|  %>
  <%= f.label :location %>&nbsp;&nbsp;
  <%= f.collection_select :location_id, Location.all, :id, :name %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.submit %>
<% end %>

app/views/trees/new.html.erb
<h1>Plant a Tree</h1>
<br><br>

<%= form_for @tree do |f|  %>
  <%= f.label :species %>&nbsp;&nbsp;
  <%= f.select :species, options_for_select(TREE_LIST) %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.label :location %>&nbsp;&nbsp;
  <%= f.collection_select :location_id, @locations, :id, :name %>&nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.submit %>
<% end %>

app/views/trees/show.html.erb
<% require 'wikipedia' %>
<h1><%= @tree.species %></h1>
<h2>Located at: <%= link_to Location.find(@tree.location_id).name, location_path(@tree.location_id) %></h2>
<div class="show-page-list">
  <h3>Planted by: <%= link_to User.find(@tree.user_id).name, user_path(@tree.user_id) %></h3>
</div><br><br><br><br><br>
<div class="tree-image">
  <%= image_tag Wikipedia.find(@tree.species).main_image_url %>
</div>

app/views/users/edit.html.erb
<h1> Edit <%=@user.name%>  </h1>
  <ul>
   <%=form_for @user do|f| %>
      <li><%=f.label "Name" %></li>
      <li><%=f.text_field :name %></li>
      <% end  %>
      </ul>

app/views/users/index.html.erb
<h1> 👩‍🌾 🌾 Users 👨🏿‍🌾 🌾 </h1>

  <ul>
  <% @users.each do |user| %>
  <li><%= link_to user.name, user_path(user)  %></li>
  <%end%>
  </ul>

app/views/users/new.html.erb
<h1> Create new User </h1>

  <ul>
    <%=form_for @user do |f| %>
    <%=f.label :name %>
    <%=f.text_field :name %><br>
    <%=f.label :password %>
    <%=f.text_field :password %><br>
    <%=f.submit %>
    <%end%>
    </ul>
    <br>  <a href="javascript:history.go(-1)"> Go Back </a> <br>

app/views/users/show.html.erb
<h1><%= @user.name %> has helped plant the following <%= @trees.count %> trees:</h1>
<div class="show-page-list">
  <% @trees.each do |tree| %>
    <h3><%= link_to tree.species, tree %> in <%= link_to tree.location.name, tree.location %></h3>
    <% if tree != @trees.last %>
      <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h3>
    <% end %>
  <% end %>
</div>